defmodule SmartKioskCore.Schemas.UserToken do
  @moduledoc """
  Auth tokens generated by phx.gen.auth.
  Handles session, email confirmation, and password reset tokens.
  """
  use Ecto.Schema
  import Ecto.Query

  alias SmartKioskCore.Schemas.User

  @primary_key {:id, :binary_id, autogenerate: true}
  @foreign_key_type :binary_id

  @hash_algorithm :sha256
  @rand_size 32

  # Session tokens do not expire (user logs out manually).
  # Email tokens expire after 1 day, password reset after 10 minutes.
  @session_validity_in_days 60
  @confirm_validity_in_days 1
  @reset_password_validity_in_minutes 10
  @change_email_validity_in_days 7

  schema "users_tokens" do
    field :token,      :binary
    field :context,    :string
    field :sent_to,    :string

    belongs_to :user, User

    timestamps(type: :utc_datetime, updated_at: false)
  end

  @doc "Generates a token for session (browser cookie)."
  def build_session_token(user) do
    token = :crypto.strong_rand_bytes(@rand_size)
    {token, %__MODULE__{token: token, context: "session", user_id: user.id}}
  end

  @doc "Queries the token and user by session token, respecting expiry."
  def verify_session_token_query(token) do
    query =
      from t in __MODULE__,
        join: u in assoc(t, :user),
        where: t.token == ^token and t.context == "session",
        where: t.inserted_at > ago(@session_validity_in_days, "day"),
        select: u

    {:ok, query}
  end

  @doc "Builds an email token (hashed for storage, raw sent to user)."
  def build_email_token(user, context) do
    build_hashed_token(user, context, user.email)
  end

  defp build_hashed_token(user, context, sent_to) do
    token = :crypto.strong_rand_bytes(@rand_size)
    hashed = :crypto.hash(@hash_algorithm, token)

    {Base.url_encode64(token, padding: false),
     %__MODULE__{
       token: hashed,
       context: context,
       sent_to: sent_to,
       user_id: user.id
     }}
  end

  @doc "Verifies an email confirmation token."
  def verify_email_token_query(token, context) do
    case Base.url_decode64(token, padding: false) do
      {:ok, decoded} ->
        hashed = :crypto.hash(@hash_algorithm, decoded)

        query =
          from t in __MODULE__,
            join: u in assoc(t, :user),
            where: t.token == ^hashed,
            where: t.context == ^context,
            where: t.inserted_at > ago(@confirm_validity_in_days, "day"),
            select: u

        {:ok, query}

      :error ->
        :error
    end
  end

  @doc "Verifies a password reset token (10 min expiry)."
  def verify_reset_password_token_query(token) do
    case Base.url_decode64(token, padding: false) do
      {:ok, decoded} ->
        hashed = :crypto.hash(@hash_algorithm, decoded)

        query =
          from t in __MODULE__,
            join: u in assoc(t, :user),
            where: t.token == ^hashed,
            where: t.context == "reset_password",
            where: t.inserted_at > ago(@reset_password_validity_in_minutes, "minute"),
            select: u

        {:ok, query}

      :error ->
        :error
    end
  end

  @doc "Verifies a change-email token."
  def verify_change_email_token_query(token, context) do
    case Base.url_decode64(token, padding: false) do
      {:ok, decoded} ->
        hashed = :crypto.hash(@hash_algorithm, decoded)

        query =
          from t in __MODULE__,
            join: u in assoc(t, :user),
            where: t.token == ^hashed,
            where: t.context == ^context,
            where: t.inserted_at > ago(@change_email_validity_in_days, "day"),
            select: {u, t.sent_to}

        {:ok, query}

      :error ->
        :error
    end
  end
end
